In [27]:
import pandas as pd
med = pd.read_csv('world.csv')
med2=med[['洲名','國家','日期','總確診數','新增確診數']]
med2['日期']=pd.to_datetime(med['日期'])
med3=med2.set_index('日期')
med3.query('國家=="台灣"')

/tmp/ipykernel_44830/3534328161.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  med2['日期']=pd.to_datetime(med['日期'])

            洲名  國家     總確診數  新增確診數
日期
2020-01-16  亞洲  台灣        0      0
2020-01-17  亞洲  台灣        0      0
2020-01-18  亞洲  台灣        0      0
2020-01-19  亞洲  台灣        0      0
2020-01-20  亞洲  台灣        0      0
...         ..  ..      ...    ...
2022-07-02  亞洲  台灣  3837856  34807
2022-07-03  亞洲  台灣  3870528  32672
2022-07-04  亞洲  台灣  3893643  23115
2022-07-05  亞洲  台灣  3929627  35984
2022-07-06  亞洲  台灣  3964188  34561

[903 rows x 4 columns]

In [15]:
med2= med.query('國家=="台灣"')

In [26]:
med3=med2.sort_values(by='新增確診數', ascending=False)
med3.iloc[:5]

,ID,iso_code,洲名,國家,總確診數,新增確診數,七天移動平均新增確診數,總死亡數,新增死亡數,七天移動平均新增死亡數,...,七天移動平均疫苗新增接種劑數,每百人接種疫苗劑數,每百人接種疫苗人數,疫情控管指數,總人口數,中位數年紀,70歲以上人口比例,平均壽命,解除隔離數,解封指數
日期,,,,,,,,,,,,,,,,,,,,,
2022-05-14,164836,TWN,亞洲,台灣,699824,128954,61607.857,1049,81,21.857,...,76312.0,0.00,0.00,26.85,23855008,42.2,8.353,80.46,14835,46.24
2022-05-09,164831,TWN,亞洲,台灣,397504,128935,37792.714,931,35,9.000,...,87600.0,223.06,83.27,26.85,23855008,42.2,8.353,80.46,14835,25.86
2022-05-27,164849,TWN,亞洲,台灣,1735067,94796,82682.286,1784,126,71.429,...,83406.0,229.17,85.45,26.85,23855008,42.2,8.353,80.46,14835,116.08
2022-05-19,164841,TWN,亞洲,台灣,1070561,89420,71384.429,1235,59,38.143,...,75623.0,226.26,84.29,26.85,23855008,42.2,8.353,80.46,14835,71.25
2022-05-25,164847,TWN,亞洲,台灣,1558380,89361,82462.714,1554,76,54.000,...,71461.0,228.02,84.85,26.85,23855008,42.2,8.353,80.46,14835,104.15

In [24]:
me4= med2.set_index('日期', inplace=True, drop=False)

KeyError: "None of ['日期'] are in the columns"

In [25]:
med2.info()

<class 'pandas.core.frame.DataFrame'>
Index: 903 entries, 2020-01-16 to 2022-07-06
Data columns (total 32 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   ID              903 non-null    int64
 1   iso_code        903 non-null    object
 2   洲名              903 non-null    object
 3   國家              903 non-null    object
 4   總確診數            903 non-null    int64
 5   新增確診數           903 non-null    int64
 6   七天移動平均新增確診數     903 non-null    float64
 7   總死亡數            903 non-null    int64
 8   新增死亡數           903 non-null    int64
 9   七天移動平均新增死亡數     903 non-null    float64
 10  每百萬人確診數         903 non-null    float64
 11  每百萬人死亡數         903 non-null    float64
 12  傳染率             903 non-null    float64
 13  新增檢驗件數          903 non-null    int64
 14  總檢驗件數           903 non-null    int64
 15  每千人檢驗件數         903 non-null    float64
 16  七天移動平均新增檢驗件數    903 non-null    float64
 17  陽性率             903 non-null    float64
 18  每確診案例相對檢驗數量     903 non-null    float64
 19  疫苗總接種總劑數        903 non-null    int64
 20  疫苗總接種人數         903 non-null    int64
 21  疫苗新增接種劑數        903 non-null    int64
 22  七天移動平均疫苗新增接種劑數  903 non-null    float64
 23  每百人接種疫苗劑數       903 non-null    float64
 24  每百人接種疫苗人數       903 non-null    float64
 25  疫情控管指數          903 non-null    float64
 26  總人口數            903 non-null    int64
 27  中位數年紀           903 non-null    float64
 28  70歲以上人口比例       903 non-null    float64
 29  平均壽命            903 non-null    float64
 30  解除隔離數           903 non-null    int64
 31  解封指數            903 non-null    float64
dtypes: float64(17), int64(12), object(3)
memory usage: 232.8+ KB

In [ ]:
pd.to