In [2]:
import numpy as np
np.linspace(-3,3) #引數值呼叫

array([-3.        , -2.87755102, -2.75510204, -2.63265306, -2.51020408,
       -2.3877551 , -2.26530612, -2.14285714, -2.02040816, -1.89795918,
       -1.7755102 , -1.65306122, -1.53061224, -1.40816327, -1.28571429,
       -1.16326531, -1.04081633, -0.91836735, -0.79591837, -0.67346939,
       -0.55102041, -0.42857143, -0.30612245, -0.18367347, -0.06122449,
        0.06122449,  0.18367347,  0.30612245,  0.42857143,  0.55102041,
        0.67346939,  0.79591837,  0.91836735,  1.04081633,  1.16326531,
        1.28571429,  1.40816327,  1.53061224,  1.65306122,  1.7755102 ,
        1.89795918,  2.02040816,  2.14285714,  2.26530612,  2.3877551 ,
        2.51020408,  2.63265306,  2.75510204,  2.87755102,  3.        ])

In [5]:
array=np.linspace(-3,3,num=100) #num 引數名稱呼叫
array*10

array([-30.        , -29.39393939, -28.78787879, -28.18181818,
       -27.57575758, -26.96969697, -26.36363636, -25.75757576,
       -25.15151515, -24.54545455, -23.93939394, -23.33333333,
       -22.72727273, -22.12121212, -21.51515152, -20.90909091,
       -20.3030303 , -19.6969697 , -19.09090909, -18.48484848,
       -17.87878788, -17.27272727, -16.66666667, -16.06060606,
       -15.45454545, -14.84848485, -14.24242424, -13.63636364,
       -13.03030303, -12.42424242, -11.81818182, -11.21212121,
       -10.60606061, -10.        ,  -9.39393939,  -8.78787879,
        -8.18181818,  -7.57575758,  -6.96969697,  -6.36363636,
        -5.75757576,  -5.15151515,  -4.54545455,  -3.93939394,
        -3.33333333,  -2.72727273,  -2.12121212,  -1.51515152,
        -0.90909091,  -0.3030303 ,   0.3030303 ,   0.90909091,
         1.51515152,   2.12121212,   2.72727273,   3.33333333,
         3.93939394,   4.54545455,   5.15151515,   5.75757576,
         6.36363636,   6.96969697,   7.57575758,   8.18181818,
         8.78787879,   9.39393939,  10.        ,  10.60606061,
        11.21212121,  11.81818182,  12.42424242,  13.03030303,
        13.63636364,  14.24242424,  14.84848485,  15.45454545,
        16.06060606,  16.66666667,  17.27272727,  17.87878788,
        18.48484848,  19.09090909,  19.6969697 ,  20.3030303 ,
        20.90909091,  21.51515152,  22.12121212,  22.72727273,
        23.33333333,  23.93939394,  24.54545455,  25.15151515,
        25.75757576,  26.36363636,  26.96969697,  27.57575758,
        28.18181818,  28.78787879,  29.39393939,  30.        ])

In [6]:
np.random.randint(50,high=101,size=101) #high  不包含 tuple裡面不可修改，用小括號,引數值要依順序，引數名稱可不依序

array([69, 89, 96, 86, 79, 61, 89, 88, 62, 78])

In [15]:
content= np.random.randint(50,high=101,size=(50,5)) #tuple,二維表格陣列，50個學生,5個分數

In [18]:
import pandas as pd
df1 = pd.DataFrame (data=content, 
                    index=range(1,51),
                    columns=['國','英','數','地','歷'])
df1

      國    英    數   地    歷
1    89   83   64  75   81
2    71   53   88  50   88
3    57   81   80  74   66
4    72   70   72  83   62
5    79   73   78  71   52
6    67   87   57  64   86
7    66   60   83  76   65
8    53   55   53  80   78
9    76   78   56  62   66
10   76   52   97  92   54
11   91   75   56  85   53
12   80   60   80  78   52
13   52   68   97  76   84
14   83   56   84  73   83
15   98   86   68  71   69
16   62   95   91  68   98
17   83   97   82  70   75
18   74  100   63  61   87
19   81   93   68  81   99
20   92   84   98  76   88
21   60   54   51  65   50
22   97   92   93  87   52
23   90   87   76  83   68
24   87   79   89  83   73
25   62   83   95  52   78
26   65   85   68  54   70
27   81   50   83  66   61
28   76   91  100  52  100
29   54   52   50  62   64
30   71   57   65  58   74
31   59   79   86  62   84
32   67   69   82  97   64
33   81   92   58  69   87
34   95   92   88  52   73
35   84   70   72  72   80
36   73   66   51  86   61
37   86   82   95  63   92
38   58   51   79  93   88
39   72   63   81  80  100
40   93   86   61  77   79
41   85   52   59  65   52
42   84   52   78  58   65
43   67   96   53  51   63
44   69   57   70  60   64
45   59   68   52  88   92
46   91   66   97  50   50
47   83   68   79  73   58
48   99   68   82  65   82
49   51   53   51  70   73
50  100   96   66  90   80

In [19]:
df1['國']+df1['英']

1     172
2     124
3     138
4     142
5     152
6     154
7     126
8     108
9     154
10    128
11    166
12    140
13    120
14    139
15    184
16    157
17    180
18    174
19    174
20    176
21    114
22    189
23    177
24    166
25    145
26    150
27    131
28    167
29    106
30    128
31    138
32    136
33    173
34    187
35    154
36    139
37    168
38    109
39    135
40    179
41    137
42    136
43    163
44    126
45    127
46    157
47    151
48    167
49    104
50    196
dtype: int64